### ISSUE TITLE
find by uuid is not working

### ISSUE THREAD

**Issue by satanworker** [masumsoft/express-cassandra#73]
I'm trying to find user by id, but it seems not work at all
model 
module.exports = {
  fields: {
    id: {
      type: "uuid",
      default: {
        "$db_function": "uuid()"
      }
    },

and then in query, I'm trying to find it, but even with uuid from string have no effect, but searching by email is working perfectly

**Comment by masumsoft** [comment]
Could you please add the example code you are trying in query? Looks like the uuid is generated using `uuid()`  db function, so you need to know the uuid generated in the db to query it later. If you need to know the uuid beforehand, then you have to use the `models.uuid()` function to generate the uuid in your code and later try finding it like the following:

```
var myid = models.uuid();
var modelobj = new models.instance.Mymodel({id: myid});
modelobj.save(function(err){
    // now as the id is saved we can query using the generated id because we generated it in the code and not using db function
    models.instance.Mymodel.find({id: myid}, function(err, data){
        console.log(data.id);
    });
});
```

**Comment by shatayuD** [comment]
I'm using latest i.e. 2.2.3 version.
I tried to query with partition key uuid. I'm just returning promise here to caller method
```
var models = require('express-cassandra');
return models.instance.Customer.findAsync({id:id})
```
But got exception as 

```
  cause: { apollo.model.validator.invalidvalue: Invalid Value: "8cc86755-b435-4b40-89dd-ed9baa9de116" for Field: id (Type: uuid)
    at f (C:\projects\generator\myapp\node_modules\express-cassandra\lib\orm\apollo_error.js:174:15)
    at Object.f [as get_db_value_expression] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:97:11)
    at buildQueryRelations (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:324:24)
    at Object.f [as extract_query_relations] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:392:5)
    at C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:461:41
    at Array.forEach (<anonymous>)
    at Object.f [as _parse_query_object] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:401:28)
    at Object.f [as get_filter_clause] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:472:29)
    at Object.f [as get_where_clause] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\utils\parser.js:507:17)
    at Function.f [as get_find_query] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\orm\base_model.js:296:28)
    at Function.f [as find] (C:\projects\generator\myapp\node_modules\express-cassandra\lib\orm\base_model.js:761:26)
    at Function.tryCatcher (C:\projects\generator\myapp\node_modules\bluebird\js\release\util.js:16:23)
    at Function.ret [as findAsync] (eval at makeNodePromisifiedEval (C:\projects\generator\myapp\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:14:23)
```

I also referred to  [question on stackoverflow](https://stackoverflow.com/questions/42905893/querying-cassandra-with-uuid-from-nodejs) 
But I dont want to index the other fields as of now 
CustomerModel.js is as follows : 

```
module.exports = {
    fields: {
        id: { type: "uuid", default: { "$db_function": "uuid()" } },
        name: {
            type: "text",
            rule: {
                validators: [
                    {
                        validator: function (value) { return value < 10 },
                        message: function (value) { return 'maximum length allowed is 10, passed length is ' + value.length }
                    },
                    {
                        validator: function (value) { return value.length > 0 },
                        message: function (value) { return 'name is required' }
                    }
                ]

            }
        },
        address: "text",
        city: "text",
        created: "timestamp"
    },
    key: ["id"]
}

```
Kindly help me to sort this out. is it that id is queried with quotes to cassandra for uuid field ? Please guide me how to solve this issue.
Also I'm not saving it like shown here, I have id from where I want to find the model.
