### ISSUE TITLE
Not able to use UDTs in Models

### ISSUE THREAD

**Issue by giancarlocosta** [masumsoft/express-cassandra#94]
I am trying to define a UDT that I can use in my models here:

```
models.setDirectory( __dirname + '/models').bindAsync({
      clientOptions: {
        contactPoints: [process.env.DB_HOST],
        keyspace: process.env.DB_KEYSPACE,
        protocolOptions: { port: 9042 },
        queryOptions: {consistency: models.consistencies.one}
      },
      ormOptions: {
        udts: {
          test_udt: {
            alias: 'text',
            phone_number: 'text',
            country_code: 'int'
          }
        },
        defaultReplicationStrategy : {
          class: 'SimpleStrategy',
          replication_factor: 1
        },
        migration: 'safe',
        createKeyspace: true
      }
    });

```

In the /models folder I have this model:

```
module.exports = {
  fields: {
    id: 'text',
    name: 'set<frozen <test_udt>>',
  },
  key:['id']
}
```

but I get an error:

```
apollo.model.validator.invalidschema: Given schema field type is not supported for: name(undefined)
    at f (/Users/gcosta/Desktop/Team/eLect/election-service/node_modules/express-cassandra/lib/orm/apollo_error.js:174:15)
    at Object.add_model (/Users/gcosta/Desktop/Team/eLect/election-service/node_modules/express-cassandra/lib/orm/apollo.js:474:13)
    at /Users/gcosta/Desktop/Team/eLect/election-service/node_modules/express-cassandra/lib/expressCassandra.js:60:52
    at /Users/gcosta/Desktop/Team/eLect/election-service/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/gcosta/Desktop/Team/eLect/election-service/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/gcosta/Desktop/Team/eLect/election-service/node_modules/async/lib/async.js:209:22)
    at /Users/gcosta/Desktop/Team/eLect/election-service/node_modules/express-cassandra/lib/expressCassandra.js:45:13
    at FSReqWrap.oncomplete (fs.js:123:15) file=server/middleware/error.js, metadata=undefined
```

Any ideas why this is happening?

**Comment by masumsoft** [comment]
Your model definition is not proper. You cannot use type definition like this in your model schema. You need to use the frozen type and declare the typeDef like the following:

```
module.exports = {
  fields: {
    id: 'text',
    name: {
      type: 'frozen',
      typeDef: '<set <frozen<test_udt>>>'
    },
  },
  key:['id']
}
```

**Comment by giancarlocosta** [comment]
Ah, my mistake. Thank you. The following is what I was aiming for:
```
name: {
      type: 'set',
      typeDef: '<frozen <test_udt>>'
    }
```
